# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SuperficialWaterExtend
                                 A QGIS plugin
 Calcular el area y la variacion temporal de las aguas superficiales
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-10-26
        copyright            : (C) 2021 by Manuel Guerra Jardines
        email                : gmanuelj4147@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SuperficialWaterExtend class from file SuperficialWaterExtend.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .superficial_water_extend import SuperficialWaterExtend
    return SuperficialWaterExtend(iface)
